/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\or32x1" *)
(* top =  1  *)
(* src = "or32x1.v:3.1-11.10" *)
module or32x1(or_input0, or_input1, or_output);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _122_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _123_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _124_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _125_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _126_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _127_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _128_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _129_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _130_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _131_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _132_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _133_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _134_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _135_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _136_;
  (* src = "or32x1.v:4.18-4.27" *)
  wire _137_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _138_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _139_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _140_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _141_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _142_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _143_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _144_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _145_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _146_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _147_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _148_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _149_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _150_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _151_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _152_;
  (* src = "or32x1.v:5.18-5.27" *)
  wire _153_;
  (* src = "or32x1.v:6.17-6.26" *)
  wire _154_;
  (* src = "or32x1.v:4.18-4.27" *)
  input [15:0] or_input0;
  wire [15:0] or_input0;
  (* src = "or32x1.v:5.18-5.27" *)
  input [15:0] or_input1;
  wire [15:0] or_input1;
  (* src = "or32x1.v:6.17-6.26" *)
  output or_output;
  wire or_output;
  assign _056_ = ~_129_;
  assign _057_ = ~_122_;
  assign _058_ = ~_131_;
  assign _059_ = ~_130_;
  assign _060_ = ~_133_;
  assign _061_ = ~_132_;
  assign _062_ = ~_135_;
  assign _063_ = ~_134_;
  assign _064_ = ~_137_;
  assign _065_ = ~_136_;
  assign _066_ = ~_124_;
  assign _067_ = ~_123_;
  assign _068_ = ~_126_;
  assign _069_ = ~_125_;
  assign _070_ = ~_128_;
  assign _071_ = ~_127_;
  assign _072_ = ~_145_;
  assign _073_ = ~_138_;
  assign _074_ = ~_147_;
  assign _075_ = ~_146_;
  assign _076_ = ~_149_;
  assign _077_ = ~_148_;
  assign _078_ = ~_151_;
  assign _079_ = ~_150_;
  assign _080_ = ~_153_;
  assign _081_ = ~_152_;
  assign _082_ = ~_140_;
  assign _083_ = ~_139_;
  assign _084_ = ~_142_;
  assign _085_ = ~_141_;
  assign _086_ = ~_144_;
  assign _087_ = ~_143_;
  assign _088_ = ~(_076_ & _079_);
  assign _089_ = ~_088_;
  assign _090_ = ~(_073_ & _074_);
  assign _091_ = ~_090_;
  assign _092_ = ~(_089_ & _091_);
  assign _093_ = ~_092_;
  assign _094_ = ~(_085_ & _086_);
  assign _095_ = ~_094_;
  assign _096_ = ~(_080_ & _083_);
  assign _097_ = ~_096_;
  assign _098_ = ~(_095_ & _097_);
  assign _099_ = ~_098_;
  assign _100_ = ~(_093_ & _099_);
  assign _101_ = ~_100_;
  assign _102_ = ~(_061_ & _062_);
  assign _103_ = ~_102_;
  assign _104_ = ~(_056_ & _059_);
  assign _105_ = ~_104_;
  assign _106_ = ~(_103_ & _105_);
  assign _107_ = ~_106_;
  assign _108_ = ~(_065_ & _066_);
  assign _109_ = ~_108_;
  assign _110_ = ~(_068_ & _071_);
  assign _111_ = ~_110_;
  assign _112_ = ~(_109_ & _111_);
  assign _113_ = ~_112_;
  assign _114_ = ~(_107_ & _113_);
  assign _115_ = ~_114_;
  assign _116_ = ~(_101_ & _115_);
  assign _117_ = ~_116_;
  assign _118_ = ~(_077_ & _078_);
  assign _119_ = ~_118_;
  assign _120_ = ~(_072_ & _075_);
  assign _121_ = ~_120_;
  assign _030_ = ~(_119_ & _121_);
  assign _031_ = ~_030_;
  assign _032_ = ~(_084_ & _087_);
  assign _033_ = ~_032_;
  assign _034_ = ~(_081_ & _082_);
  assign _035_ = ~_034_;
  assign _036_ = ~(_033_ & _035_);
  assign _037_ = ~_036_;
  assign _038_ = ~(_031_ & _037_);
  assign _039_ = ~_038_;
  assign _040_ = ~(_060_ & _063_);
  assign _041_ = ~_040_;
  assign _042_ = ~(_057_ & _058_);
  assign _043_ = ~_042_;
  assign _044_ = ~(_041_ & _043_);
  assign _045_ = ~_044_;
  assign _046_ = ~(_069_ & _070_);
  assign _047_ = ~_046_;
  assign _048_ = ~(_064_ & _067_);
  assign _049_ = ~_048_;
  assign _050_ = ~(_047_ & _049_);
  assign _051_ = ~_050_;
  assign _052_ = ~(_045_ & _051_);
  assign _053_ = ~_052_;
  assign _054_ = ~(_039_ & _053_);
  assign _055_ = ~_054_;
  assign _154_ = ~(_117_ & _055_);
  assign _129_ = or_input0[1];
  assign _122_ = or_input0[0];
  assign _131_ = or_input0[3];
  assign _130_ = or_input0[2];
  assign _133_ = or_input0[5];
  assign _132_ = or_input0[4];
  assign _135_ = or_input0[7];
  assign _134_ = or_input0[6];
  assign _137_ = or_input0[9];
  assign _136_ = or_input0[8];
  assign _124_ = or_input0[11];
  assign _123_ = or_input0[10];
  assign _126_ = or_input0[13];
  assign _125_ = or_input0[12];
  assign _128_ = or_input0[15];
  assign _127_ = or_input0[14];
  assign _145_ = or_input1[1];
  assign _138_ = or_input1[0];
  assign _147_ = or_input1[3];
  assign _146_ = or_input1[2];
  assign _149_ = or_input1[5];
  assign _148_ = or_input1[4];
  assign _151_ = or_input1[7];
  assign _150_ = or_input1[6];
  assign _153_ = or_input1[9];
  assign _152_ = or_input1[8];
  assign _140_ = or_input1[11];
  assign _139_ = or_input1[10];
  assign _142_ = or_input1[13];
  assign _141_ = or_input1[12];
  assign _144_ = or_input1[15];
  assign _143_ = or_input1[14];
  assign or_output = _154_;
endmodule
