/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\DFF" *)
(* top =  1  *)
(* src = "cells.v:14.1-19.10" *)
module DFF(C, D, Q);
  (* src = "cells.v:15.7-15.8" *)
  input C;
  wire C;
  (* src = "cells.v:15.10-15.11" *)
  input D;
  wire D;
  (* src = "cells.v:16.12-16.13" *)
  output Q;
  reg Q;
  (* src = "cells.v:17.1-18.9" *)
  always @(posedge C)
    Q <= D;
endmodule
