/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\truth_table" *)
(* top =  1  *)
(* src = "truth_table.v:3.1-23.10" *)
module truth_table(CLK, RST, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  (* src = "truth_table.v:5.11-5.14" *)
  wire _012_;
  wire _013_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire _014_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _015_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _016_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _017_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _018_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _019_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _020_;
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _056_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _057_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _058_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _059_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _060_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _061_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _062_;
  (* src = "truth_table.v:6.21-6.24" *)
  wire _063_;
  (* force_downto = 32'd1 *)
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _064_;
  (* force_downto = 32'd1 *)
  (* src = "truth_table.v:20.20-20.27|/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _065_;
  (* src = "truth_table.v:4.11-4.14" *)
  input CLK;
  wire CLK;
  (* src = "truth_table.v:5.11-5.14" *)
  input RST;
  wire RST;
  (* src = "truth_table.v:6.21-6.24" *)
  output [7:0] out;
  reg [7:0] out;
  assign _022_ = ~_057_;
  assign _014_ = ~_056_;
  assign _023_ = ~_059_;
  assign _024_ = ~_058_;
  assign _025_ = ~_061_;
  assign _026_ = ~_060_;
  assign _027_ = ~_062_;
  assign _028_ = ~_063_;
  assign _029_ = ~(_057_ & _056_);
  assign _030_ = ~_029_;
  assign _031_ = ~(_058_ & _030_);
  assign _032_ = ~_031_;
  assign _033_ = ~(_059_ & _032_);
  assign _034_ = ~_033_;
  assign _035_ = ~(_060_ & _034_);
  assign _036_ = ~_035_;
  assign _037_ = ~(_061_ & _036_);
  assign _038_ = ~_037_;
  assign _039_ = ~(_062_ & _038_);
  assign _040_ = ~_039_;
  assign _041_ = ~(_063_ & _040_);
  assign _013_ = ~(_012_ & _041_);
  assign _042_ = ~(_022_ & _014_);
  assign _043_ = ~(_029_ & _042_);
  assign _015_ = ~_043_;
  assign _044_ = ~(_024_ & _029_);
  assign _045_ = ~(_031_ & _044_);
  assign _016_ = ~_045_;
  assign _046_ = ~(_023_ & _031_);
  assign _047_ = ~(_033_ & _046_);
  assign _017_ = ~_047_;
  assign _048_ = ~(_026_ & _033_);
  assign _049_ = ~(_035_ & _048_);
  assign _018_ = ~_049_;
  assign _050_ = ~(_025_ & _035_);
  assign _051_ = ~(_037_ & _050_);
  assign _019_ = ~_051_;
  assign _052_ = ~(_027_ & _037_);
  assign _053_ = ~(_039_ & _052_);
  assign _020_ = ~_053_;
  assign _054_ = ~(_028_ & _039_);
  assign _055_ = ~(_041_ & _054_);
  assign _021_ = ~_055_;
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[0] <= 1'h0;
    else out[0] <= _064_[0];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[1] <= 1'h0;
    else out[1] <= _065_[1];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[2] <= 1'h0;
    else out[2] <= _065_[2];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[3] <= 1'h0;
    else out[3] <= _065_[3];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[4] <= 1'h0;
    else out[4] <= _065_[4];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[5] <= 1'h0;
    else out[5] <= _065_[5];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[6] <= 1'h0;
    else out[6] <= _065_[6];
  (* src = "truth_table.v:8.1-22.4" *)
  always @(posedge CLK)
    if (_000_) out[7] <= 1'h0;
    else out[7] <= _065_[7];
  assign _064_[7:1] = out[7:1];
  assign _065_[0] = _064_[0];
  assign _057_ = out[1];
  assign _056_ = out[0];
  assign _059_ = out[3];
  assign _058_ = out[2];
  assign _061_ = out[5];
  assign _060_ = out[4];
  assign _062_ = out[6];
  assign _063_ = out[7];
  assign _012_ = RST;
  assign _000_ = _013_;
  assign _064_[0] = _014_;
  assign _065_[1] = _015_;
  assign _065_[2] = _016_;
  assign _065_[3] = _017_;
  assign _065_[4] = _018_;
  assign _065_[5] = _019_;
  assign _065_[6] = _020_;
  assign _065_[7] = _021_;
endmodule
