/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "bus_compare.v:3.1-15.10" *)
module compare_buses(bus0, bus1, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "bus_compare.v:4.18-4.22" *)
  input [7:0] bus0;
  wire [7:0] bus0;
  (* src = "bus_compare.v:5.18-5.22" *)
  input [7:0] bus1;
  wire [7:0] bus1;
  (* src = "bus_compare.v:6.17-6.20" *)
  output out;
  wire out;
  NOT _35_ (
    .A(bus1[0]),
    .Y(_00_)
  );
  NOT _36_ (
    .A(bus0[0]),
    .Y(_01_)
  );
  NOT _37_ (
    .A(bus1[1]),
    .Y(_02_)
  );
  NOT _38_ (
    .A(bus0[1]),
    .Y(_03_)
  );
  NOT _39_ (
    .A(bus1[2]),
    .Y(_04_)
  );
  NOT _40_ (
    .A(bus0[2]),
    .Y(_05_)
  );
  NOT _41_ (
    .A(bus1[3]),
    .Y(_06_)
  );
  NOT _42_ (
    .A(bus0[3]),
    .Y(_07_)
  );
  NOT _43_ (
    .A(bus1[4]),
    .Y(_08_)
  );
  NOT _44_ (
    .A(bus0[4]),
    .Y(_09_)
  );
  NOT _45_ (
    .A(bus1[5]),
    .Y(_10_)
  );
  NOT _46_ (
    .A(bus0[5]),
    .Y(_11_)
  );
  NOT _47_ (
    .A(bus1[6]),
    .Y(_12_)
  );
  NOT _48_ (
    .A(bus0[6]),
    .Y(_13_)
  );
  NOT _49_ (
    .A(bus1[7]),
    .Y(_14_)
  );
  NOT _50_ (
    .A(bus0[7]),
    .Y(_15_)
  );
  NAND2 _51_ (
    .A(bus1[5]),
    .B(_11_),
    .Y(_16_)
  );
  NAND2 _52_ (
    .A(_10_),
    .B(bus0[5]),
    .Y(_17_)
  );
  NAND2 _53_ (
    .A(bus1[6]),
    .B(_13_),
    .Y(_18_)
  );
  NAND2 _54_ (
    .A(_12_),
    .B(bus0[6]),
    .Y(_19_)
  );
  NAND2 _55_ (
    .A(bus1[0]),
    .B(_01_),
    .Y(_20_)
  );
  NAND2 _56_ (
    .A(_00_),
    .B(bus0[0]),
    .Y(_21_)
  );
  NAND2 _57_ (
    .A(bus1[7]),
    .B(_15_),
    .Y(_22_)
  );
  NAND2 _58_ (
    .A(_14_),
    .B(bus0[7]),
    .Y(_23_)
  );
  NAND2 _59_ (
    .A(bus1[1]),
    .B(_03_),
    .Y(_24_)
  );
  NAND2 _60_ (
    .A(_02_),
    .B(bus0[1]),
    .Y(_25_)
  );
  NAND2 _61_ (
    .A(bus1[4]),
    .B(_09_),
    .Y(_26_)
  );
  NAND2 _62_ (
    .A(_08_),
    .B(bus0[4]),
    .Y(_27_)
  );
  NAND2 _63_ (
    .A(bus1[2]),
    .B(_05_),
    .Y(_28_)
  );
  NAND2 _64_ (
    .A(_04_),
    .B(bus0[2]),
    .Y(_29_)
  );
  NAND2 _65_ (
    .A(bus1[3]),
    .B(_07_),
    .Y(_30_)
  );
  NAND2 _66_ (
    .A(_06_),
    .B(bus0[3]),
    .Y(_31_)
  );
  NAND4 _67_ (
    .A(_20_),
    .B(_21_),
    .C(_28_),
    .D(_29_),
    .Y(_32_)
  );
  NAND6 _68_ (
    .A(_16_),
    .B(_17_),
    .C(_18_),
    .D(_19_),
    .E(_22_),
    .F(_23_),
    .Y(_33_)
  );
  NAND6 _69_ (
    .A(_24_),
    .B(_25_),
    .C(_26_),
    .D(_27_),
    .E(_30_),
    .F(_31_),
    .Y(_34_)
  );
  NOR3 _70_ (
    .A(_32_),
    .B(_33_),
    .C(_34_),
    .Y(out)
  );
endmodule
