/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\equal_to_one" *)
(* top =  1  *)
(* src = "equal_to_one.v:3.1-16.10" *)
module equal_to_one(input0, boolean);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  (* src = "equal_to_one.v:5.16-5.23" *)
  wire _014_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _015_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _016_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _017_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _018_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _019_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _020_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _021_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _022_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _023_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _024_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _025_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _026_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _027_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _028_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _029_;
  (* src = "equal_to_one.v:4.18-4.24" *)
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  (* src = "equal_to_one.v:5.16-5.23" *)
  output boolean;
  wire boolean;
  (* src = "equal_to_one.v:4.18-4.24" *)
  input [15:0] input0;
  wire [15:0] input0;
  assign _031_ = ~_022_;
  assign _032_ = ~_024_;
  assign _033_ = ~_023_;
  assign _034_ = ~_026_;
  assign _035_ = ~_025_;
  assign _036_ = ~_028_;
  assign _037_ = ~_027_;
  assign _038_ = ~_030_;
  assign _039_ = ~_029_;
  assign _040_ = ~_017_;
  assign _041_ = ~_016_;
  assign _042_ = ~_019_;
  assign _043_ = ~_018_;
  assign _044_ = ~_021_;
  assign _045_ = ~_020_;
  assign _046_ = ~(_034_ & _035_);
  assign _047_ = ~_046_;
  assign _048_ = ~(_036_ & _037_);
  assign _049_ = ~_048_;
  assign _050_ = ~(_047_ & _049_);
  assign _051_ = ~_050_;
  assign _052_ = ~(_015_ & _031_);
  assign _053_ = ~_052_;
  assign _054_ = ~(_032_ & _033_);
  assign _055_ = ~_054_;
  assign _056_ = ~(_053_ & _055_);
  assign _057_ = ~_056_;
  assign _058_ = ~(_051_ & _057_);
  assign _059_ = ~_058_;
  assign _060_ = ~(_042_ & _043_);
  assign _061_ = ~_060_;
  assign _062_ = ~(_044_ & _045_);
  assign _063_ = ~_062_;
  assign _064_ = ~(_061_ & _063_);
  assign _065_ = ~_064_;
  assign _066_ = ~(_038_ & _039_);
  assign _067_ = ~_066_;
  assign _068_ = ~(_040_ & _041_);
  assign _069_ = ~_068_;
  assign _070_ = ~(_067_ & _069_);
  assign _071_ = ~_070_;
  assign _072_ = ~(_065_ & _071_);
  assign _073_ = ~_072_;
  assign _074_ = ~(_059_ & _073_);
  assign _014_ = ~_074_;
  assign _015_ = input0[0];
  assign _022_ = input0[1];
  assign _024_ = input0[3];
  assign _023_ = input0[2];
  assign _026_ = input0[5];
  assign _025_ = input0[4];
  assign _028_ = input0[7];
  assign _027_ = input0[6];
  assign _030_ = input0[9];
  assign _029_ = input0[8];
  assign _017_ = input0[11];
  assign _016_ = input0[10];
  assign _019_ = input0[13];
  assign _018_ = input0[12];
  assign _021_ = input0[15];
  assign _020_ = input0[14];
  assign boolean = _014_;
endmodule
