/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\PCAdder" *)
(* top =  1  *)
(* src = "PCAdder.v:3.1-11.10" *)
module PCAdder(PCIn, PCOut);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _021_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _022_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _023_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _024_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _025_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _026_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _027_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _028_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _029_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _030_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _031_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _032_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _033_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _034_;
  (* src = "PCAdder.v:4.14-4.18" *)
  wire _035_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _036_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _037_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _038_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _039_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _040_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _041_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _042_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _043_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _044_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _045_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _046_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _047_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _048_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _049_;
  (* src = "PCAdder.v:5.19-5.24" *)
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  (* src = "PCAdder.v:4.14-4.18" *)
  input [15:0] PCIn;
  wire [15:0] PCIn;
  (* src = "PCAdder.v:5.19-5.24" *)
  output [15:0] PCOut;
  wire [15:0] PCOut;
  assign _042_ = ~_027_;
  assign _060_ = ~_022_;
  assign _061_ = ~_023_;
  assign _062_ = ~_035_;
  assign _063_ = ~_021_;
  assign _064_ = ~_033_;
  assign _065_ = ~_034_;
  assign _066_ = ~_031_;
  assign _067_ = ~_032_;
  assign _068_ = ~_029_;
  assign _069_ = ~_030_;
  assign _070_ = ~_028_;
  assign _071_ = ~_024_;
  assign _072_ = ~_025_;
  assign _073_ = ~_026_;
  assign _074_ = ~(_027_ & _028_);
  assign _075_ = ~_074_;
  assign _076_ = ~(_029_ & _075_);
  assign _077_ = ~_076_;
  assign _078_ = ~(_030_ & _077_);
  assign _079_ = ~_078_;
  assign _080_ = ~(_031_ & _079_);
  assign _081_ = ~_080_;
  assign _082_ = ~(_032_ & _081_);
  assign _083_ = ~_082_;
  assign _084_ = ~(_033_ & _083_);
  assign _085_ = ~_084_;
  assign _086_ = ~(_034_ & _085_);
  assign _087_ = ~_086_;
  assign _088_ = ~(_035_ & _087_);
  assign _089_ = ~_088_;
  assign _090_ = ~(_021_ & _089_);
  assign _091_ = ~_090_;
  assign _092_ = ~(_022_ & _091_);
  assign _093_ = ~_092_;
  assign _094_ = ~(_023_ & _093_);
  assign _095_ = ~_094_;
  assign _096_ = ~(_024_ & _095_);
  assign _097_ = ~_096_;
  assign _098_ = ~(_071_ & _094_);
  assign _099_ = ~(_096_ & _098_);
  assign _039_ = ~_099_;
  assign _100_ = ~(_025_ & _097_);
  assign _101_ = ~_100_;
  assign _102_ = ~(_072_ & _096_);
  assign _103_ = ~(_100_ & _102_);
  assign _040_ = ~_103_;
  assign _104_ = ~(_026_ & _100_);
  assign _105_ = ~(_073_ & _101_);
  assign _041_ = ~(_104_ & _105_);
  assign _106_ = ~(_042_ & _070_);
  assign _107_ = ~(_074_ & _106_);
  assign _043_ = ~_107_;
  assign _108_ = ~(_068_ & _074_);
  assign _109_ = ~(_076_ & _108_);
  assign _044_ = ~_109_;
  assign _110_ = ~(_069_ & _076_);
  assign _111_ = ~(_078_ & _110_);
  assign _045_ = ~_111_;
  assign _112_ = ~(_066_ & _078_);
  assign _113_ = ~(_080_ & _112_);
  assign _046_ = ~_113_;
  assign _114_ = ~(_067_ & _080_);
  assign _115_ = ~(_082_ & _114_);
  assign _047_ = ~_115_;
  assign _116_ = ~(_064_ & _082_);
  assign _117_ = ~(_084_ & _116_);
  assign _048_ = ~_117_;
  assign _118_ = ~(_065_ & _084_);
  assign _051_ = ~(_086_ & _118_);
  assign _049_ = ~_051_;
  assign _052_ = ~(_062_ & _086_);
  assign _053_ = ~(_088_ & _052_);
  assign _050_ = ~_053_;
  assign _054_ = ~(_063_ & _088_);
  assign _055_ = ~(_090_ & _054_);
  assign _036_ = ~_055_;
  assign _056_ = ~(_060_ & _090_);
  assign _057_ = ~(_092_ & _056_);
  assign _037_ = ~_057_;
  assign _058_ = ~(_061_ & _092_);
  assign _059_ = ~(_094_ & _058_);
  assign _038_ = ~_059_;
  assign PCOut[0] = PCIn[0];
  assign _027_ = PCIn[1];
  assign PCOut[1] = _042_;
  assign _022_ = PCIn[11];
  assign _023_ = PCIn[12];
  assign _035_ = PCIn[9];
  assign _021_ = PCIn[10];
  assign _033_ = PCIn[7];
  assign _034_ = PCIn[8];
  assign _031_ = PCIn[5];
  assign _032_ = PCIn[6];
  assign _029_ = PCIn[3];
  assign _030_ = PCIn[4];
  assign _028_ = PCIn[2];
  assign _024_ = PCIn[13];
  assign PCOut[13] = _039_;
  assign _025_ = PCIn[14];
  assign PCOut[14] = _040_;
  assign _026_ = PCIn[15];
  assign PCOut[15] = _041_;
  assign PCOut[2] = _043_;
  assign PCOut[3] = _044_;
  assign PCOut[4] = _045_;
  assign PCOut[5] = _046_;
  assign PCOut[6] = _047_;
  assign PCOut[7] = _048_;
  assign PCOut[8] = _049_;
  assign PCOut[9] = _050_;
  assign PCOut[10] = _036_;
  assign PCOut[11] = _037_;
  assign PCOut[12] = _038_;
endmodule
