/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\equal_to_one_8bit" *)
(* top =  1  *)
(* src = "equal_to_one_8bit.v:3.1-17.10" *)
module equal_to_one_8bit(A, Y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _06_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _07_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _08_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _09_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _10_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _11_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _12_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  wire _13_;
  (* src = "equal_to_one_8bit.v:6.16-6.17" *)
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  (* src = "equal_to_one_8bit.v:5.17-5.18" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "equal_to_one_8bit.v:6.16-6.17" *)
  output Y;
  wire Y;
  assign _15_ = ~_07_;
  assign _16_ = ~_09_;
  assign _17_ = ~_08_;
  assign _18_ = ~_11_;
  assign _19_ = ~_10_;
  assign _20_ = ~_13_;
  assign _21_ = ~_12_;
  assign _22_ = ~(_18_ & _19_);
  assign _23_ = ~_22_;
  assign _24_ = ~(_20_ & _21_);
  assign _25_ = ~_24_;
  assign _26_ = ~(_23_ & _25_);
  assign _27_ = ~_26_;
  assign _28_ = ~(_06_ & _15_);
  assign _29_ = ~_28_;
  assign _30_ = ~(_16_ & _17_);
  assign _31_ = ~_30_;
  assign _32_ = ~(_29_ & _31_);
  assign _33_ = ~_32_;
  assign _34_ = ~(_27_ & _33_);
  assign _14_ = ~_34_;
  assign _06_ = A[0];
  assign _07_ = A[1];
  assign _09_ = A[3];
  assign _08_ = A[2];
  assign _11_ = A[5];
  assign _10_ = A[4];
  assign _13_ = A[7];
  assign _12_ = A[6];
  assign Y = _14_;
endmodule
