/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\control" *)
(* top =  1  *)
(* src = "control.v:3.1-77.10" *)
module control(gcd_done, start, compare, CLK, relprime_done, CTRL1, CTRL2, CTRL3, CTRL4, CTRL5, CTRL7, CTRL8, CTRL9);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "control.v:9.17-9.22" *)
  wire _06_;
  (* src = "control.v:10.14-10.19" *)
  wire _07_;
  (* src = "control.v:12.14-12.19" *)
  wire _08_;
  (* src = "control.v:13.14-13.19" *)
  wire _09_;
  (* src = "control.v:15.14-15.19" *)
  wire _10_;
  (* src = "control.v:6.9-6.16" *)
  wire _11_;
  (* src = "control.v:4.12-4.20" *)
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "control.v:8.9-8.22" *)
  wire _22_;
  (* src = "control.v:5.9-5.14" *)
  wire _23_;
  (* src = "control.v:7.9-7.12" *)
  input CLK;
  wire CLK;
  (* src = "control.v:9.17-9.22" *)
  output CTRL1;
  wire CTRL1;
  (* src = "control.v:10.14-10.19" *)
  output CTRL2;
  wire CTRL2;
  (* src = "control.v:11.14-11.19" *)
  output CTRL3;
  wire CTRL3;
  (* src = "control.v:12.14-12.19" *)
  output CTRL4;
  wire CTRL4;
  (* src = "control.v:13.14-13.19" *)
  output CTRL5;
  wire CTRL5;
  (* src = "control.v:14.14-14.19" *)
  output CTRL7;
  wire CTRL7;
  (* src = "control.v:15.14-15.19" *)
  output CTRL8;
  wire CTRL8;
  (* src = "control.v:16.14-16.19" *)
  output CTRL9;
  wire CTRL9;
  (* src = "control.v:6.9-6.16" *)
  input compare;
  wire compare;
  (* src = "control.v:4.12-4.20" *)
  input gcd_done;
  wire gcd_done;
  (* src = "control.v:8.9-8.22" *)
  input relprime_done;
  wire relprime_done;
  (* src = "control.v:5.9-5.14" *)
  input start;
  wire start;
  assign _13_ = ~_23_;
  assign _14_ = ~_12_;
  assign _15_ = ~_22_;
  assign _16_ = ~_11_;
  assign _17_ = ~(_13_ & _14_);
  assign _18_ = ~_17_;
  assign _19_ = ~(_13_ & _22_);
  assign _09_ = ~(_17_ & _19_);
  assign _06_ = ~_09_;
  assign _20_ = ~(_15_ & _16_);
  assign _21_ = ~_20_;
  assign _10_ = ~(_09_ & _20_);
  assign _07_ = ~_10_;
  assign _08_ = ~(_18_ & _21_);
  assign CTRL3 = start;
  assign CTRL7 = CTRL4;
  assign CTRL9 = CTRL1;
  assign _23_ = start;
  assign _12_ = gcd_done;
  assign _22_ = relprime_done;
  assign CTRL5 = _09_;
  assign _11_ = compare;
  assign CTRL2 = _07_;
  assign CTRL1 = _06_;
  assign CTRL8 = _10_;
  assign CTRL4 = _08_;
endmodule
