/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\equal_to_zero_8bit" *)
(* top =  1  *)
(* src = "equal_to_zero_8bit.v:3.1-17.10" *)
module equal_to_zero_8bit(A, Y);
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _00_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _01_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _02_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _03_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _04_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _05_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _06_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  wire _07_;
  (* src = "equal_to_zero_8bit.v:6.16-6.17" *)
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  (* src = "equal_to_zero_8bit.v:5.17-5.18" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "equal_to_zero_8bit.v:6.16-6.17" *)
  output Y;
  wire Y;
  assign _09_ = ~_01_;
  assign _10_ = ~_00_;
  assign _11_ = ~_03_;
  assign _12_ = ~_02_;
  assign _13_ = ~_05_;
  assign _14_ = ~_04_;
  assign _15_ = ~_07_;
  assign _16_ = ~_06_;
  assign _17_ = ~(_13_ & _14_);
  assign _18_ = ~_17_;
  assign _19_ = ~(_15_ & _16_);
  assign _20_ = ~_19_;
  assign _21_ = ~(_18_ & _20_);
  assign _22_ = ~_21_;
  assign _23_ = ~(_09_ & _10_);
  assign _24_ = ~_23_;
  assign _25_ = ~(_11_ & _12_);
  assign _26_ = ~_25_;
  assign _27_ = ~(_24_ & _26_);
  assign _28_ = ~_27_;
  assign _29_ = ~(_22_ & _28_);
  assign _08_ = ~_29_;
  assign Y = _08_;
  assign _01_ = A[1];
  assign _00_ = A[0];
  assign _03_ = A[3];
  assign _02_ = A[2];
  assign _05_ = A[5];
  assign _04_ = A[4];
  assign _07_ = A[7];
  assign _06_ = A[6];
endmodule
