/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\add_two_8bit_buses" *)
(* top =  1  *)
(* src = "add_two_8bit_buses.v:3.1-12.10" *)
module add_two_8bit_buses(A, B, Y);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _032_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _033_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _034_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _035_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _036_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _037_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _038_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  wire _039_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _040_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _041_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _042_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _043_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _044_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _045_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _046_;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  wire _047_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _048_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _049_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _050_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _051_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _052_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _053_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _054_;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  (* src = "add_two_8bit_buses.v:5.17-5.18" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "add_two_8bit_buses.v:6.17-6.18" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "add_two_8bit_buses.v:7.22-7.23" *)
  output [7:0] Y;
  wire [7:0] Y;
  assign _070_ = ~_041_;
  assign _071_ = ~_033_;
  assign _072_ = ~_040_;
  assign _073_ = ~_032_;
  assign _074_ = ~_042_;
  assign _075_ = ~_034_;
  assign _076_ = ~_043_;
  assign _077_ = ~_035_;
  assign _078_ = ~_044_;
  assign _079_ = ~_036_;
  assign _080_ = ~_045_;
  assign _081_ = ~_037_;
  assign _082_ = ~_046_;
  assign _083_ = ~_038_;
  assign _084_ = ~_047_;
  assign _085_ = ~_039_;
  assign _086_ = ~(_040_ & _032_);
  assign _087_ = ~_086_;
  assign _088_ = ~(_041_ & _033_);
  assign _089_ = ~(_070_ & _071_);
  assign _090_ = ~(_088_ & _089_);
  assign _091_ = ~_090_;
  assign _092_ = ~(_087_ & _091_);
  assign _093_ = ~(_086_ & _090_);
  assign _094_ = ~(_092_ & _093_);
  assign _049_ = ~_094_;
  assign _095_ = ~(_088_ & _092_);
  assign _096_ = ~_095_;
  assign _097_ = ~(_042_ & _034_);
  assign _098_ = ~(_074_ & _075_);
  assign _099_ = ~(_097_ & _098_);
  assign _100_ = ~_099_;
  assign _101_ = ~(_095_ & _100_);
  assign _102_ = ~(_096_ & _099_);
  assign _103_ = ~(_101_ & _102_);
  assign _050_ = ~_103_;
  assign _104_ = ~(_097_ & _101_);
  assign _105_ = ~_104_;
  assign _106_ = ~(_043_ & _035_);
  assign _107_ = ~(_076_ & _077_);
  assign _108_ = ~(_106_ & _107_);
  assign _109_ = ~_108_;
  assign _110_ = ~(_105_ & _109_);
  assign _111_ = ~(_104_ & _108_);
  assign _051_ = ~(_110_ & _111_);
  assign _112_ = ~(_044_ & _036_);
  assign _113_ = ~(_078_ & _079_);
  assign _114_ = ~(_112_ & _113_);
  assign _115_ = ~_114_;
  assign _116_ = ~(_104_ & _107_);
  assign _117_ = ~(_105_ & _106_);
  assign _118_ = ~(_107_ & _117_);
  assign _119_ = ~(_106_ & _116_);
  assign _120_ = ~(_115_ & _119_);
  assign _121_ = ~(_114_ & _118_);
  assign _122_ = ~(_120_ & _121_);
  assign _052_ = ~_122_;
  assign _123_ = ~(_112_ & _120_);
  assign _124_ = ~_123_;
  assign _125_ = ~(_045_ & _037_);
  assign _126_ = ~(_080_ & _081_);
  assign _127_ = ~(_125_ & _126_);
  assign _128_ = ~_127_;
  assign _129_ = ~(_123_ & _127_);
  assign _130_ = ~(_124_ & _128_);
  assign _053_ = ~(_129_ & _130_);
  assign _131_ = ~(_046_ & _038_);
  assign _132_ = ~(_082_ & _083_);
  assign _133_ = ~(_131_ & _132_);
  assign _134_ = ~_133_;
  assign _135_ = ~(_123_ & _126_);
  assign _136_ = ~(_124_ & _125_);
  assign _137_ = ~(_126_ & _136_);
  assign _138_ = ~(_125_ & _135_);
  assign _139_ = ~(_134_ & _138_);
  assign _056_ = ~(_133_ & _137_);
  assign _057_ = ~(_139_ & _056_);
  assign _054_ = ~_057_;
  assign _058_ = ~(_131_ & _139_);
  assign _059_ = ~_058_;
  assign _060_ = ~(_084_ & _085_);
  assign _061_ = ~(_047_ & _039_);
  assign _062_ = ~(_047_ & _085_);
  assign _063_ = ~(_084_ & _039_);
  assign _064_ = ~(_062_ & _063_);
  assign _065_ = ~(_060_ & _061_);
  assign _066_ = ~(_059_ & _064_);
  assign _067_ = ~(_058_ & _065_);
  assign _055_ = ~(_066_ & _067_);
  assign _068_ = ~(_072_ & _073_);
  assign _069_ = ~(_086_ & _068_);
  assign _048_ = ~_069_;
  assign _041_ = B[1];
  assign _033_ = A[1];
  assign _040_ = B[0];
  assign _032_ = A[0];
  assign Y[1] = _049_;
  assign _042_ = B[2];
  assign _034_ = A[2];
  assign Y[2] = _050_;
  assign _043_ = B[3];
  assign _035_ = A[3];
  assign Y[3] = _051_;
  assign _044_ = B[4];
  assign _036_ = A[4];
  assign Y[4] = _052_;
  assign _045_ = B[5];
  assign _037_ = A[5];
  assign Y[5] = _053_;
  assign _046_ = B[6];
  assign _038_ = A[6];
  assign Y[6] = _054_;
  assign _047_ = B[7];
  assign _039_ = A[7];
  assign Y[7] = _055_;
  assign Y[0] = _048_;
endmodule
