/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\bcd_to_7seg" *)
(* top =  1  *)
(* src = "bcd_to_hex.v:3.1-29.10" *)
module bcd_to_7seg(bcd, seg);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  (* src = "bcd_to_hex.v:5.14-5.17" *)
  wire _025_;
  (* src = "bcd_to_hex.v:5.14-5.17" *)
  wire _026_;
  (* src = "bcd_to_hex.v:5.14-5.17" *)
  wire _027_;
  (* src = "bcd_to_hex.v:5.14-5.17" *)
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _083_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _084_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _085_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _086_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _087_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _088_;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  wire _089_;
  (* src = "bcd_to_hex.v:5.14-5.17" *)
  input [3:0] bcd;
  wire [3:0] bcd;
  (* src = "bcd_to_hex.v:6.19-6.22" *)
  output [6:0] seg;
  wire [6:0] seg;
  assign _029_ = ~_027_;
  assign _030_ = ~_025_;
  assign _031_ = ~_026_;
  assign _032_ = ~_028_;
  assign _033_ = ~(_027_ & _031_);
  assign _034_ = ~_033_;
  assign _035_ = ~(_028_ & _034_);
  assign _036_ = ~_035_;
  assign _037_ = ~(_030_ & _036_);
  assign _038_ = ~(_025_ & _026_);
  assign _039_ = ~(_027_ & _038_);
  assign _040_ = ~(_029_ & _026_);
  assign _041_ = ~_040_;
  assign _042_ = ~(_032_ & _040_);
  assign _043_ = ~_042_;
  assign _044_ = ~(_039_ & _043_);
  assign _045_ = ~(_037_ & _044_);
  assign _083_ = ~_045_;
  assign _046_ = ~(_025_ & _036_);
  assign _047_ = ~(_030_ & _031_);
  assign _048_ = ~(_032_ & _047_);
  assign _049_ = ~_048_;
  assign _050_ = ~(_039_ & _049_);
  assign _051_ = ~(_046_ & _050_);
  assign _084_ = ~_051_;
  assign _052_ = ~(_030_ & _033_);
  assign _053_ = ~_052_;
  assign _054_ = ~(_029_ & _031_);
  assign _055_ = ~(_028_ & _054_);
  assign _085_ = ~(_052_ & _055_);
  assign _056_ = ~(_030_ & _032_);
  assign _057_ = ~(_033_ & _040_);
  assign _058_ = ~(_056_ & _057_);
  assign _059_ = ~_058_;
  assign _060_ = ~(_053_ & _058_);
  assign _061_ = ~(_052_ & _059_);
  assign _062_ = ~(_025_ & _031_);
  assign _063_ = ~(_029_ & _062_);
  assign _064_ = ~(_027_ & _047_);
  assign _065_ = ~_064_;
  assign _066_ = ~(_038_ & _065_);
  assign _067_ = ~(_032_ & _066_);
  assign _086_ = ~(_060_ & _061_);
  assign _068_ = ~(_027_ & _062_);
  assign _069_ = ~(_028_ & _068_);
  assign _070_ = ~_069_;
  assign _071_ = ~(_030_ & _041_);
  assign _072_ = ~(_032_ & _071_);
  assign _087_ = ~(_069_ & _072_);
  assign _073_ = ~(_029_ & _038_);
  assign _074_ = ~_073_;
  assign _075_ = ~(_028_ & _074_);
  assign _076_ = ~(_032_ & _064_);
  assign _077_ = ~_076_;
  assign _078_ = ~(_046_ & _067_);
  assign _079_ = ~_078_;
  assign _088_ = ~(_075_ & _079_);
  assign _080_ = ~(_070_ & _073_);
  assign _081_ = ~(_063_ & _077_);
  assign _082_ = ~(_080_ & _081_);
  assign _089_ = ~_082_;
  assign _027_ = bcd[2];
  assign _025_ = bcd[0];
  assign _026_ = bcd[1];
  assign _028_ = bcd[3];
  assign seg[0] = _083_;
  assign seg[1] = _084_;
  assign seg[2] = _085_;
  assign seg[3] = _086_;
  assign seg[4] = _087_;
  assign seg[5] = _088_;
  assign seg[6] = _089_;
endmodule
