/* Generated by Yosys 0.28+1 (git sha1 a9c792dce, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\logical_and_8bit" *)
(* top =  1  *)
(* src = "logical_and_8bit.v:3.1-13.10" *)
module logical_and_8bit(A, B, Y);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _014_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _015_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _016_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _017_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _018_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _019_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _020_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  wire _021_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _022_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _023_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _024_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _025_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _026_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _027_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _028_;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  wire _029_;
  (* src = "logical_and_8bit.v:7.17-7.18" *)
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  (* src = "logical_and_8bit.v:5.17-5.18" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "logical_and_8bit.v:6.17-6.18" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "logical_and_8bit.v:7.17-7.18" *)
  output Y;
  wire Y;
  assign _031_ = ~_015_;
  assign _032_ = ~_014_;
  assign _033_ = ~_017_;
  assign _034_ = ~_016_;
  assign _035_ = ~_019_;
  assign _036_ = ~_018_;
  assign _037_ = ~_021_;
  assign _038_ = ~_020_;
  assign _039_ = ~_023_;
  assign _040_ = ~_022_;
  assign _041_ = ~_025_;
  assign _042_ = ~_024_;
  assign _043_ = ~_027_;
  assign _044_ = ~_026_;
  assign _045_ = ~_029_;
  assign _046_ = ~_028_;
  assign _047_ = ~(_043_ & _044_);
  assign _048_ = ~_047_;
  assign _049_ = ~(_045_ & _046_);
  assign _050_ = ~_049_;
  assign _051_ = ~(_048_ & _050_);
  assign _052_ = ~_051_;
  assign _053_ = ~(_039_ & _040_);
  assign _054_ = ~_053_;
  assign _055_ = ~(_041_ & _042_);
  assign _056_ = ~_055_;
  assign _057_ = ~(_054_ & _056_);
  assign _058_ = ~_057_;
  assign _059_ = ~(_052_ & _058_);
  assign _060_ = ~(_035_ & _036_);
  assign _061_ = ~_060_;
  assign _062_ = ~(_037_ & _038_);
  assign _063_ = ~_062_;
  assign _064_ = ~(_061_ & _063_);
  assign _065_ = ~_064_;
  assign _066_ = ~(_031_ & _032_);
  assign _067_ = ~_066_;
  assign _068_ = ~(_033_ & _034_);
  assign _069_ = ~_068_;
  assign _070_ = ~(_067_ & _069_);
  assign _071_ = ~_070_;
  assign _072_ = ~(_065_ & _071_);
  assign _073_ = ~(_059_ & _072_);
  assign _030_ = ~_073_;
  assign _015_ = A[1];
  assign _014_ = A[0];
  assign _017_ = A[3];
  assign _016_ = A[2];
  assign _019_ = A[5];
  assign _018_ = A[4];
  assign _021_ = A[7];
  assign _020_ = A[6];
  assign _023_ = B[1];
  assign _022_ = B[0];
  assign _025_ = B[3];
  assign _024_ = B[2];
  assign _027_ = B[5];
  assign _026_ = B[4];
  assign _029_ = B[7];
  assign _028_ = B[6];
  assign Y = _030_;
endmodule
